services:
  docker_manager:
    build: .
    container_name: docker_manager
    restart: unless-stopped
    ports: 
      - "3001:3001"
    environment: 
      PORT: 3001 # optionally set port, defaults to 3000 if unset
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
