services:
  docker_manager:
    build: .
    container_name: docker_manager
    restart: unless-stopped
    ports: 
      - "8080:8080"
    environment: 
      PORT: 8080 # optionally set port, defaults to 3000 if unset
